"""Postgres connection adapter for the control-plane store.

The store speaks sqlite3-shaped cursors. This wrapper runs the same SQL on
PostgreSQL so persistence tests use a real server, not a mock.
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import Self


def postgres_statements(schema: str) -> list[str]:
    statements: list[str] = []
    for raw in schema.split(";"):
        stmt = raw.strip()
        if not stmt or stmt.upper().startswith("PRAGMA"):
            continue
        stmt = stmt.replace(
            "INTEGER PRIMARY KEY AUTOINCREMENT",
            "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        )
        statements.append(stmt)
    return statements


class PgRow(Mapping):
    def __init__(self, names: list[str], values: tuple) -> None:
        self._names = names
        self._values = values
        self._map = dict(zip(names, values, strict=True))

    def __getitem__(self, key: str | int):
        if isinstance(key, int):
            return self._values[key]
        return self._map[key]

    def __iter__(self):
        return iter(self._names)

    def __len__(self) -> int:
        return len(self._names)


class PgCursor:
    def __init__(self, raw, lastrowid: int | None) -> None:
        self._raw = raw
        self.lastrowid = lastrowid
        self.rowcount = raw.rowcount

    def _wrap(self, row):
        if row is None:
            return None
        names = [item[0] for item in self._raw.description]
        return PgRow(names, row)

    def fetchone(self):
        return self._wrap(self._raw.fetchone())

    def fetchall(self):
        return [self._wrap(row) for row in self._raw.fetchall()]

    def __iter__(self):
        return iter(self.fetchall())


class PgConnection:
    def __init__(self, raw) -> None:
        self.raw = raw

    def __enter__(self) -> Self:
        return self

    def __exit__(self, exc_type, exc, tb) -> bool:
        if exc_type is None:
            self.raw.commit()
        else:
            self.raw.rollback()
        return False

    def execute(self, sql: str, params: tuple = ()) -> PgCursor:
        translated = sql.replace("?", "%s")
        cur = self.raw.cursor()
        cur.execute(translated, params)
        lastrowid = None
        if translated.lstrip().upper().startswith("INSERT"):
            lastrowid = _lastval(self.raw)
        return PgCursor(cur, lastrowid)

    def executescript(self, schema: str) -> None:
        for stmt in postgres_statements(schema):
            self.raw.cursor().execute(stmt)


def _lastval(raw) -> int | None:
    import psycopg2

    raw.cursor().execute("SAVEPOINT cp_lastid")
    try:
        cur = raw.cursor()
        cur.execute("SELECT lastval()")
        value = cur.fetchone()[0]
    except psycopg2.Error:
        raw.cursor().execute("ROLLBACK TO SAVEPOINT cp_lastid")
        return None
    raw.cursor().execute("RELEASE SAVEPOINT cp_lastid")
    return int(value)


def connect(dsn: str) -> PgConnection:
    import psycopg2

    raw = psycopg2.connect(dsn)
    raw.autocommit = False
    return PgConnection(raw)
